backend:
    name: github
    repo: taro0079/TarosBlog

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
    - name: "posts"
      label: "Posts"
      folder: "content/posts"
      create: true
      slug: "{{slug}}"
      fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Published Date", name: "date", widget: "date"}
        - {label: "published", name: "published", widget: "boolean", default: true}
        - {label: "description", name: "description", widget: "Text"}
        - {label: "Body", name: "body", widget: "markdown"}
